language: python
python:
  - 2.7
  - pypy
  # - 3.2 # Depends on consistent_hash supporting python 3 https://github.com/yummybian/consistent-hash/issues/8
  # - 3.3
  # - 3.4
install:
  - pip install -r test-requirements.txt
  - pip install -e .
script: nosetests
after_success:
  - coveralls
deploy:
  user: sprockets
  provider: pypi
  on:
    python: 2.7
    tags: true
    all_branches: true
  password:
    secure: "UFxlqmRDVHsXOlKedFtVwJEBu4qqu1/l3DFvgLnysqyLUQd6VhvIV4YaXGJiHFCFc5wPn0TKy+SvAwoM8Ecni0jpd0DdKcB74HZoOPongZN6c4kdOstkBsTbi28+5hsaFIzQqf5uJI+lcpxsQ5DT4e+7rzYi3XR/WQ08x8DVEjQ="
services:
  - redis-server
